### PR TITLE
Port serverstatus-client.py to python3

### PR DESCRIPTION
**Pull request by ChillerDragon**
Did not do a full test but it connected to the server from [BotoX repo](https://github.com/BotoX/ServerStatus/tree/master/server) I do not know if ddnet server setup is different. There are some weird looking encoding things now in the output but it authenticates :)
```
$ python3 serverstatus-client.py 
Connecting...
b'Authentication successful. Access granted.\n\x00\x00'
b'You are connecting via: IPv4\n\x00\x00'

```

### CODE REVIEW

**Comment by def-** [comment]
print(data) should be print(data.decode('utf-8')).

**Comment by def-** [comment]
Also, please update ddnet-setup with python3 instead of python2

**Comment by ChillerDragon** [comment]
Looks fine now :)
```
$ python3 serverstatus-client.py 
Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4
```

**Comment by ChillerDragon** [comment]
Seems like both python2 and python3 are needed now because those seem to use python2
```
client/tunings.py
client/convert.py
client/commands.py
client/settings.py
servers/scripts/saveteamsrace.py
servers/scripts/saverace.py
```

**Comment by def-** [comment]
Those scripts are not used on the regular game servers.

**Comment by def-** [comment]
CPU percentage isn't working btw

**Comment by def-** [comment]
fixed

**Pull request merged**
